POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYjU0MyIsImlkIjoiNjgzNzFiYWUyNzc1MTU3OGEyZjc0MzU1IiwiaWF0IjoxNzQ4NDQyMDc0fQ.3FpZFKymd70rjIjCU9csYSxxYKgH3hFZliW3szx0JUM

{
  "title": "Titlej",
  "author": "Authorghjghjghj",
  "url": "ffgodfjgodfgfd.com",
  "likes": 5,
  "userId": "68370b5627866ea51864c596"
}