
DELETE http://localhost:3003/api/blogs/6837477e1d7ef8935c1812b5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYjU0MyIsImlkIjoiNjgzNzUxMTgzMDdlZTgwNmVjYjQzMWM1IiwiaWF0IjoxNzQ4NDU3ODA4fQ.T86YlT5v3MaVOW_qVNy5C1fISfFrDhfRjfnZTm4G6QM
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvZzEyMyIsImlkIjoiNjgzNzBiNTYyNzg2NmVhNTE4NjRjNTk2IiwiaWF0IjoxNzQ4NDQ4Mzc2fQ.2LlwLMF3zKiFIQFL-xzejaufOuD6IhvUVrltF3e7ZVI
